### ISSUE TITLE
Отсутствую выпуски

### ISSUE THREAD

**Issue by SGmuwa** [Elco-/RayMarching#1]
В репозитории отсутствуют [выпуски](https://github.com/Elco-/RayMarching/releases). Из-за чего я не могу попробовать поиграться с RayMarching без Unity. Например, на Windows, Linux, Mac, Android, WebGL.

**Comment by ArtemOnigiri** [comment]
> В репозитории отсутствуют [выпуски](https://github.com/Elco-/RayMarching/releases). Из-за чего я не могу попробовать поиграться с RayMarching без Unity. Например, на Windows, Linux, Mac, Android, WebGL.

Этот проект был полностью рассчитан на просмотр из окна редактирования Unity, но можно найти много подобных проектов на Shadertoy, например тот, по которому я изучал эту тему: https://www.shadertoy.com/view/wdf3zl
