### ISSUE TITLE
Плагин для работы шейдеров в редакторе

### ISSUE THREAD

**Issue by SupinePandora43** [Elco-/RayMarching#2]
В видео упомянут плагин который позволяет работать шейдерам не только в игре ("Game"), но и в редакторе ("Scene").
Что это за плагин???

**Comment by ArtemOnigiri** [comment]
> В видео упомянут плагин который позволяет работать шейдерам не только в игре ("Game"), но и в редакторе ("Scene").
> Что это за плагин???

Это просто скрипт, от которого надо унаследоваться и повесить это на камеру: http://framebunker.com/blog/viewing-image-effects-in-the-scene-view/
Вот здесь есть пример его использования: https://flafla2.github.io/2016/10/01/raymarching.html

**Comment by SupinePandora43** [comment]
спасибо

**Comment by SupinePandora43** [comment]
@Elco- что ты скажешь насчёт DOTS???
